//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PV_analysis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double 开关器件电压裕量 {
            get {
                return ((double)(this["开关器件电压裕量"]));
            }
            set {
                this["开关器件电压裕量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double 开关器件电流裕量 {
            get {
                return ((double)(this["开关器件电流裕量"]));
            }
            set {
                this["开关器件电流裕量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double 变压器窗口利用系数 {
            get {
                return ((double)(this["变压器窗口利用系数"]));
            }
            set {
                this["变压器窗口利用系数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double 电感最大气隙长度 {
            get {
                return ((double)(this["电感最大气隙长度"]));
            }
            set {
                this["电感最大气隙长度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double 电容电压裕量 {
            get {
                return ((double)(this["电容电压裕量"]));
            }
            set {
                this["电容电压裕量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double 电容电流裕量 {
            get {
                return ((double)(this["电容电流裕量"]));
            }
            set {
                this["电容电流裕量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double 电流密度 {
            get {
                return ((double)(this["电流密度"]));
            }
            set {
                this["电流密度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 给定谐振电感 {
            get {
                return ((bool)(this["给定谐振电感"]));
            }
            set {
                this["给定谐振电感"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 电感磁芯型号 {
            get {
                return ((string)(this["电感磁芯型号"]));
            }
            set {
                this["电感磁芯型号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int 电感磁芯数 {
            get {
                return ((int)(this["电感磁芯数"]));
            }
            set {
                this["电感磁芯数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double 电感气隙长度 {
            get {
                return ((double)(this["电感气隙长度"]));
            }
            set {
                this["电感气隙长度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 电感绕线型号 {
            get {
                return ((string)(this["电感绕线型号"]));
            }
            set {
                this["电感绕线型号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int 电感绕线匝数 {
            get {
                return ((int)(this["电感绕线匝数"]));
            }
            set {
                this["电感绕线匝数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 给定谐振电容 {
            get {
                return ((bool)(this["给定谐振电容"]));
            }
            set {
                this["给定谐振电容"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 电容型号1 {
            get {
                return ((string)(this["电容型号1"]));
            }
            set {
                this["电容型号1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int 电容串联数 {
            get {
                return ((int)(this["电容串联数"]));
            }
            set {
                this["电容串联数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int 电容并联数 {
            get {
                return ((int)(this["电容并联数"]));
            }
            set {
                this["电容并联数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool 给定变压器 {
            get {
                return ((bool)(this["给定变压器"]));
            }
            set {
                this["给定变压器"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 变压器磁芯型号 {
            get {
                return ((string)(this["变压器磁芯型号"]));
            }
            set {
                this["变压器磁芯型号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int 变压器磁芯数 {
            get {
                return ((int)(this["变压器磁芯数"]));
            }
            set {
                this["变压器磁芯数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 变压器原边绕线型号 {
            get {
                return ((string)(this["变压器原边绕线型号"]));
            }
            set {
                this["变压器原边绕线型号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int 变压器原边匝数 {
            get {
                return ((int)(this["变压器原边匝数"]));
            }
            set {
                this["变压器原边匝数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 变压器副边绕线型号 {
            get {
                return ((string)(this["变压器副边绕线型号"]));
            }
            set {
                this["变压器副边绕线型号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int 变压器副边匝数 {
            get {
                return ((int)(this["变压器副边匝数"]));
            }
            set {
                this["变压器副边匝数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double 最大工作磁密 {
            get {
                return ((double)(this["最大工作磁密"]));
            }
            set {
                this["最大工作磁密"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int 电容总个数上限 {
            get {
                return ((int)(this["电容总个数上限"]));
            }
            set {
                this["电容总个数上限"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int 电容不同型号数量上限 {
            get {
                return ((int)(this["电容不同型号数量上限"]));
            }
            set {
                this["电容不同型号数量上限"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 电容型号2 {
            get {
                return ((string)(this["电容型号2"]));
            }
            set {
                this["电容型号2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 电容型号3 {
            get {
                return ((string)(this["电容型号3"]));
            }
            set {
                this["电容型号3"] = value;
            }
        }
    }
}
